### ISSUE TITLE
Can't insert, delete or update

### ISSUE THREAD

**Issue by davidweb-co** [sleeping-owl/admin#55]
Error when press button is
```
BadMethodCallException in Builder.php line 1992:
Call to undefined method Illuminate\Database\Query\Builder::validate()
```
Are you have solution?

Thanks

**Comment by davidweb-co** [comment]
problem is solved use SleepingOwl\Models\SleepingOwlModel

but new problem coming
```
MassAssignmentException in Model.php line 404: _token
```

**Comment by davidweb-co** [comment]
the issue is gone with adding protected $guarded = ['id']; at model, thank you :)

**Comment by rigelk** [comment]
@davidweb-co i’m still having issues at deleting entities after extending them with the `SleepingOwl\Models\SleepingOwlModel`.

Might the provided `_token` be wrong ?
